# Generated by Django 2.0.7 on 2018-11-17 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_lank', to='ticket.Lank')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_winning', models.BooleanField(default=False)),
                ('lot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_id', to='ticket.LotteryLot')),
            ],
        ),
    ]
